### PR TITLE
Update control mappings, create FedRAMP High control selections

### PR DESCRIPTION
**Pull request by shawndwells**
- Update FedRAMP-{low moderate} with refreshed control mappings
- Sort control mappings numerically
- Add FedRAMP-High, update opencontrol.yaml
- Update README to include compliance masonry and fedramp-templater example commands

### CODE REVIEW

**Comment by shawndwells** [comment]
@geramirez Are you still maintaining these files? Looks like they haven't been touched for awhile and wanted to double check! If not, would @afeld be appropriate to review/merge?

Thanks!

**Comment by geramirez** [comment]
I am maintaining these anymore. Sorry!

**Comment by shawndwells** [comment]
Appreciate the reply, @geramirez!

@afeld: I can self-merge, but that's not very open source-y. Happy to take on maintenance of these mappings though.

**Comment by shawndwells** [comment]
Given the original maintainer has moved on, going to self-ack and step-up to maintain in the interim.

**Pull request merged**
