### PR TITLE
create EOL notice

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by shawndwells** [comment]
Wasn't sure how to handle expiring old repos. Suggesting updating with the attached language -- gives 90 day notice for downstreams to update to the new repo. Afterwards this repo could be removed.

**Comment by gregelin** [comment]
Starting to review this PR.

**Comment by shawndwells** [comment]
Thanks @gregelin. Once some notice is created (e.g. language in this PR), suggest Archiving the project to make the transition even more obvious.

**Comment by shawndwells** [comment]
bump @gregelin

**Comment by shawndwells** [comment]
It's been long enough. Self merging.

**Pull request merged**
